name: Build and push images to DockerHub

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    name: Build and Push image to DockerHub
    runs-on: ubuntu-latest
    steps:   
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx      
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:vtapp/backend"
          push: true
          tags: duongtm3102/test-backend:latest, ${{ github.run_number }}
      
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:vtapp/frontend"
          push: true
          tags: duongtm3102/test-frontend:latest, ${{ github.run_number }}
